### ISSUE TITLE
Remove remaining `DaGdBaseApp` usages

### ISSUE THREAD

**Issue by danopia** [dagd/dagd#40]
* [ ] `DaGdBreakController` - fixed by #39
* [ ] `DaGdDNSController` - fixed by #39
* [ ] `DaGdLeftPadController` - fixed by #39
* [ ] `DaGdMetricsController` - fixed by #38 
* [ ] `DaGdHelpController` - will be replaced by newhelp
* [ ] `DaGdImageController` - it does some graphic stuff, possibly a more complex `DaGdController` port
* [ ] `DaGdCommanderController` - maybe we'll delete this?
